import "@/global/global.css";
import AppProvider from "./context/AppProvider";
import { fontTripSans } from "../../public/fonts/font-family";
import Header from "./_components/common/header/Header";
import ToolBar from "./_components/common/toolbar/ToolBar";
import Footer from "../../components/section/footer/Footer";

export const metadata = {
  title: "Homepage - Hong Hao Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white ${fontTripSans.className}`}>
        <AppProvider>
          <Header />
          <main>{children}</main>
          <Footer />
          <ToolBar />
        </AppProvider>
      </body>
    </html>
  );
}
