import "@/global/global.css";
import Header from "./_components/Header";
import AppProvider from "./context/AppProvider";

export const metadata = {
  title: "Homepage - Hong Hao Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white font-inter">
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
