import Image from 'next/image';
import OurTeam from '../../components/section/ourteam/OurTeam';
import Banner from './_components/sections/banner';
import BestTrips from './_components/sections/best-trips';
import Feedback from './_components/sections/feedback';
import Introduction from './_components/sections/intro-container';
import AboutUs from './_components/sections/intro-container/about-us';
import OurTour from './_components/sections/intro-container/our-tour';
import Welcome from './_components/sections/intro-container/welcome';
import Moment from './_components/sections/moment';
import Weather from './_components/sections/weather';

export const metadata = {
  title: 'Homepage - Hong Hao Travel',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      <Banner />
      <Introduction>
        <AboutUs />
        <OurTour />
        <Welcome />
      </Introduction>
      <BestTrips />
      <Moment />
      <Feedback />
      <div className="relative flex h-fit w-full bg-[linear-gradient(180deg,#122718_7.6%,rgba(18,39,24,0.71)_43.62%,#122718_79.64%)] pb-[14.5rem] max-md:pb-[6rem]">
        <Image
          alt="Hong Hao Travel"
          width={2000}
          height={1000}
          src="/images/common/bg-our-team.jpeg"
          className="absolute inset-0 z-[0] h-full w-full object-cover"
        />
        <div className="absolute inset-0 z-[1] h-full w-full bg-[linear-gradient(180deg,#122718_7.6%,rgba(18,39,24,0.71)_43.62%,#122718_79.64%)]"></div>
        <OurTeam primary />
      </div>
      <Weather />
    </>
  );
}
