import React from "react";
import BlogTitle from "./_components/BlogTitle/BlogTitle";
import BlogDetail from "./_components/BlogDetail/BlogDetail";
import BlogPlanning from "./_components/BlogPlanning/BlogPlanning";
import BlogRelated from "./_components/BlogRelated/BlogRelated";
export const metadata = {
  title: "Blog detail - Hong Hao Travel",
  description: "Generated by create next app",
};

export default function BlogDetailPage() {
  return (
    <>
      <BlogTitle />
      <BlogDetail />
      <BlogPlanning />
      <BlogRelated />
    </>
  );
}
