import { notFound } from 'next/navigation';
import BlogDetail from './_components/BlogDetail/BlogDetail';
import BlogPlanning from './_components/BlogPlanning/BlogPlanning';
import BlogRelated from './_components/BlogRelated/BlogRelated';
import BlogTitle from './_components/BlogTitle/BlogTitle';

// export const metadata = {
//   title: 'Blog detail - Hong Hao Travel',
//   description: 'Generated by create next app',
// };

export async function generateMetadata({ params }) {
  return {
    title: 'Blog detail - Hong Hao Travel',
    description: 'Generated by create next app',
  };
}

async function getBlogData() {
  return false;
}

export default async function BlogDetailPage() {
  // const blogData = await getBlogData();
  // if (!blogData) {
  //   return notFound();
  // }

  return (
    <>
      <BlogTitle />
      <BlogDetail />
      <BlogPlanning />
      <BlogRelated />
    </>
  );
}
